### ISSUE TITLE
Theme doesn't install on older Obsidian version

### ISSUE THREAD

**Issue by Psypher1** [taronull/ayu-obsidian#2]
I run an older version of Obsidian - I don't care for the updates. The theme does not install on my Obsidian 1.3.7

**Comment by taronull** [comment]
It's been locked at `1.6.0`. b2cad0bfa573269558112b14bab73ac2521ec53a allows app versions from `1.0.0`

I'm not willing to backward test all versions. Please let me know if something looks wrong. And consider upgrading the app for the theme's sake.
